version: "3.8"

services:
  app:
    image: ${APP_IMAGE_NAME}:latest
    env_file:
      - ./email-validator-gateway/.env.production
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - skyfunnel-net

  go_service:
    image: ${GO_IMAGE_NAME}:latest
    env_file:
      - ./email-validator-go/.env.production
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - skyfunnel-net

networks:
  skyfunnel-net:
