services:
  app:
    build: ./email-validator-gateway
    env_file:
      - ./email-validator-gateway/.env.production
    ports:
      - "3000:3000"
    restart: unless-stopped

  go_service:
    build: ./email-validator-go
    env_file:
      - ./email-validator-go/.env.production
    ports:
      - "8080:8080"
    restart: unless-stopped
