name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    env:
      APP_IMAGE_NAME: ${{ secrets.APP_IMAGE_NAME }}
      GO_IMAGE_NAME: ${{ secrets.GO_IMAGE_NAME }}
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN_READ_ONLY }}

      - name: Pull latest images
        run: |
          docker pull $APP_IMAGE_NAME:latest
          docker pull $GO_IMAGE_NAME:latest

      - name: Run reload.sh
        run: |
          chmod +x /home/actions/scripts/reload.sh
          APP_IMAGE_NAME=$APP_IMAGE_NAME \
          GO_IMAGE_NAME=$GO_IMAGE_NAME \
          /home/actions/scripts/reload.sh
