name: CI

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN_READ_AND_WRITE }}

      - name: Build and push app image
        run: |
          docker build -t ${{ secrets.APP_IMAGE_NAME }}:latest ./email-validator-gateway
          docker push ${{ secrets.APP_IMAGE_NAME }}:latest

      - name: Build and push go service image
        run: |
          docker build -t ${{ secrets.GO_IMAGE_NAME }}:latest ./email-validator-go
          docker push ${{ secrets.GO_IMAGE_NAME }}:latest
